import uuid
import json
from typing import List
from datetime import datetime
from backend.api.schemas.domain import (
    AnalysisInput, AnalysisQuery, ExecutionTrace, ExecutionStep, ToolResult, AnalysisTask
)
from backend.agents.task_classifier import TaskClassifier
from backend.agents.planner import AgentPlanner
from backend.geospatial.validation import validate_temporal_pair, validate_optical_sar_pair
from backend.services.llm_provider import get_llm_provider

class AgentController:
    def __init__(self):
        self.classifier = TaskClassifier()
        self.planner = AgentPlanner()
        self.llm = get_llm_provider()

    def _truncate_large_fields(self, data):
        """Recursively strip large arrays from evidence to prevent blowing up the LLM prompt."""
        if isinstance(data, dict):
            return {k: self._truncate_large_fields(v) for k, v in data.items()}
        elif isinstance(data, list):
            if len(data) > 50:
                return f"<List truncated, length={len(data)}>"
            return [self._truncate_large_fields(v) for v in data]
        return data

    def process(self, query: AnalysisQuery, input_data: AnalysisInput, image_paths: List[str]) -> ExecutionTrace:
        trace_id = str(uuid.uuid4())
        steps = []
        
        # 1. Validation Step
        steps.append(ExecutionStep(
            step_name="Input Validation",
            description="Validating input modality and geographic compatibility",
            status="pending"
        ))
        
        try:
            if input_data.input_type == "temporal_pair":
                validate_temporal_pair(input_data.images[0], input_data.images[1])
            elif input_data.input_type == "optical_sar_pair":
                validate_optical_sar_pair(input_data.images[0], input_data.images[1])
            steps[-1].status = "success"
        except Exception as e:
            steps[-1].status = "failure"
            steps[-1].error_message = str(e)
            return ExecutionTrace(trace_id=trace_id, task=AnalysisTask(task_type="unsupported"), steps=steps)

        # 2. Task Classification Step
        steps.append(ExecutionStep(
            step_name="Task Classification",
            description="Determining the required specialist capability",
            status="pending"
        ))
        
        task = self.classifier.classify(query, input_data)
        steps[-1].status = "success"
        steps[-1].description += f": {task.task_type}"

        # 3. Tool Selection Step
        steps.append(ExecutionStep(
            step_name="Tool Selection",
            description="Selecting appropriate remote sensing models",
            status="pending"
        ))
        
        try:
            tools = self.planner.plan(task)
            steps[-1].status = "success"
            tool_names = ", ".join([t.name for t in tools])
            steps[-1].description += f". Selected: {tool_names}"
        except Exception as e:
            steps[-1].status = "failure"
            steps[-1].error_message = str(e)
            return ExecutionTrace(trace_id=trace_id, task=task, steps=steps)

        # 4. Execution Step
        steps.append(ExecutionStep(
            step_name="Model Execution",
            description="Executing selected models",
            status="pending",
            tool_results=[]
        ))
        
        results = []
        for tool in tools:
            # Re-validate tool specific rules
            if not tool.validate(input_data.images, query.text):
                continue
                
            composed_query = query.text
            if results and results[-1].text:
                composed_query = f"Context from previous analysis: {results[-1].text}. Query: {query.text}"
                
            res = tool.run(image_paths, composed_query)
            results.append(res)
            steps[-1].tool_results.append(res)
            
        steps[-1].status = "success"
        
        # 5. Result Synthesis
        steps.append(ExecutionStep(
            step_name="Result Synthesis",
            description="Synthesizing final answer from model outputs",
            status="pending"
        ))
        
        def get_fallback_text():
            valid_results = [r.text for r in results if r.text]
            if valid_results:
                return "\n".join(valid_results)
            return "Analysis complete, but no text output was generated by the models."

        if not results:
            final_text = "No tools were executed successfully."
            final_evidence = None
            final_confidence = None
            steps[-1].status = "success"
        else:
            final_evidence = {}
            for r in results:
                if r.evidence:
                    # Merge dictionaries safely
                    final_evidence.update(r.evidence)
            
            if not final_evidence:
                final_evidence = None
            
            # Confidence calculation (simple average for MVP)
            confs = [r.confidence for r in results if r.confidence is not None]
            final_confidence = sum(confs) / len(confs) if confs else None
            
            # Formulate structured JSON outputs for Gemini
            serialized_results = []
            for r in results:
                safe_evidence = self._truncate_large_fields(r.evidence) if r.evidence else None
                safe_structured_data = self._truncate_large_fields(r.structured_data) if r.structured_data else None
                
                tool_data = {
                    "tool_name": r.tool_name,
                    "model_name": r.model_name,
                    "model_type": r.model_type,
                    "status": r.status,
                    "text": r.text,
                    "confidence": r.confidence,
                    "evidence": safe_evidence,
                    "structured_data": safe_structured_data,
                    "metadata": r.metadata,
                    "error_message": getattr(r, 'error_message', None)
                }
                serialized_results.append(tool_data)
                
            tool_outputs_json = json.dumps(serialized_results, indent=2)
            
            prompt = f"""You are the synthesis agent for SatQuery AI.
Your job is to read the structured outputs from remote sensing ML tools and formulate a direct, coherent, and helpful final answer to the user's query.

User Query: "{query.text}"
Task Classification: {task.task_type}

---
Tool Outputs / Evidence (JSON array of executed tool results):
{tool_outputs_json}
---

CRITICAL INSTRUCTIONS:
1. ONLY use the evidence returned by the tools above. Do not invent observations, objects, or numerical values.
2. Examine the "status" field for each tool. If a tool's status is "failure", you MUST NOT treat it as successful. Do NOT invent an observation from a failed tool. Include the error message context if relevant to explaining why the query couldn't be answered.
3. Use successful tool evidence (e.g. text, percentage_change, etc.) when available.
4. Distinguish model predictions from absolute certainty. If the confidence is low, mention the uncertainty.
5. Answer the user's actual question directly and concisely.
6. Do not claim unsupported capabilities (e.g. if the tool only outputs "0" or "yes", interpret it simply and do not hallucinate full descriptive paragraphs).
7. Provide ONLY the final answer text. Do not output JSON or wrapper text.
"""
            try:
                final_text = self.llm.generate(prompt).strip()
                steps[-1].status = "success"
            except Exception as e:
                final_text = get_fallback_text()
                steps[-1].status = "failure"
                steps[-1].error_message = f"LLM synthesis failed: {e}. Fallback used."
                if final_evidence is None:
                    final_evidence = {}
                final_evidence["synthesis_status"] = "deterministic_fallback"
        
        return ExecutionTrace(
            trace_id=trace_id,
            task=task,
            steps=steps,
            final_result=final_text,
            final_confidence=final_confidence,
            final_evidence=final_evidence,
            completed_at=datetime.utcnow()
        )
